### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by namtel-hp** [H2-invent/jitsi-admin#122]
Dear,
Please help this error
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

<img width="1440" alt="Screen Shot 2021-04-04 at 22 30 01" src="https://user-images.githubusercontent.com/62697590/113513741-55f94f80-9595-11eb-917d-387450122fad.png">

Please help me clearly setting in keycloak (client)

Thanks

**Comment by holema** [comment]
Hello @namtel-hp 
I think I found your Problem.
you have to set in the .env.local the OAUTH_KEYCLOAK_SERVER=https://sso.saza.vn/auth
I think you forgot the https:// infront of the url.

Best regads
Emanuel

**Comment by namtel-hp** [comment]
Dear Emanuel,
Thanks for your help,
It's right, I'm forgot it
So now is other problem about:
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
Check install OK, connect mysql OK.

Running: bash BranchPipeline.sh

Error:
I  41 files written to public/build
Entrypoint app [big] = 1.1e0ac3a4.js 2.ee13eda2.js app.60ef2050.css app.4d4b4789.js
Entrypoint frontend = 2.ee13eda2.js frontend.52ff5fc3.js
--------------------------------------------------------------------------
-----------------Security Check----------------------------------------------
--------------------------------------------------------------------------
                                                            
  The web service failed for an unknown reason (HTTP 403).  
                                                            


<img width="1440" alt="Screen Shot 2021-04-05 at 08 42 12" src="https://user-images.githubusercontent.com/62697590/113528468-dac28880-95ea-11eb-925d-8d98668251ea.png">

**Comment by holema** [comment]
Hello @namtel-hp 

The Security Check is indeed defect, because Symfony shut down this service.
So it is normaly no problem when the Sec-Check fails, because everythin should be already finished.

I just went to the webpage abd yesterday I got the error, but tody the jitsi-admin is down and I only get the standard debian page.
To give you better support, can you set in your .env.local:

APP_ENV=dev
APP_DEBUG=1

So I can see the error clearly.

Best regards

**Comment by namtel-hp** [comment]
Hello @holema 
Thanks for help,
Some error about permit r-w , I already fix, 
But new error: is Invalid parameter: redirect_uri

Pls help me to fix it, 

Thanks

**Comment by holema** [comment]
Hello @namtel-hp 
Do you have the php-curl  mod installed?

Best regards

**Comment by holema** [comment]
Can you try this:
https://medium.com/@narendravaghela/how-to-fix-curl-error-60-ssl-certificate-problem-80e7dafafa57#:~:text=This%20error%20occurs%20because%20the,certificate%2C%20it%20throws%20an%20error.&text=Open%20your%20php.,or%20update%20the%20following%20line.

**Comment by namtel-hp** [comment]
Hi @holema,
Thank you so much for helping me,
About error certificate : I am using myssl.pem > worked.
You are an excellent.
Note: One more thing is with meet.jit.si (worked), with my server (enable Jwt token) not working. 

Nguyen Nhat

**Comment by holema** [comment]
@namtel-hp just saw it. And I´m happy to help you.
did you already enable your jwt autentication?

**Comment by holema** [comment]
@namtel-hp 
Do you want to translate the software? If yes, I cann add your language in the next relaese and you can translate the texts at crowdin :)

Best regards

**Comment by namtel-hp** [comment]
@holema
- I already enable jwt on the meet server (https://meet.saza.vn)
- Do you want to translate the software? > Yes please.
One more thing is License ? I not clearly about that
- So maybe set something wrong: I can not edit profile and change password.
:)
Nguyen Nhat

**Comment by holema** [comment]
@namtel-hp 

- What is not clear with the license?
- so I will add you the language and your flagg and you can translate then the text, then It will be added to the software automaticaly: https://crowdin.com/project/jitsi-admin
- For the account stuff:

![image](https://user-images.githubusercontent.com/22790152/113567020-13c02480-960e-11eb-8945-2864b24c143e.png)
 In keycloak the account client must be enabled

**Comment by holema** [comment]
@namtel-hp 
did you enter the Jitsi-Meet JWT Parameter in the Server settings?

**Comment by namtel-hp** [comment]
hi @holema 
did you enter the Jitsi-Meet JWT Parameter in the Server settings?
You mean:
###> symfony/framework-bundle ###
APP_ENV=prod
APP_DEBUG=0
APP_SECRET=password APP token JITSI (Already)
And you can test with any room:
https://meet.saza.vn
with: ?jwt=
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzYXphIiwiaWF0IjoxNjE3NjI2MjYxLCJleHAiOjE2NDkxNjIyNjEsImF1ZCI6InNhemEiLCJzdWIiOiJtZWV0LnNhemEudm4iLCJuYW1lIjoiTmd1eWVuIE5oYXQiLCJlbWFpbCI6Im5hbXRlbEBleGFtcGxlLmNvbSIsInJvb20iOiIqIiwicm9sZSI6IlByb2plY3QgTWFuYWdlciIsImdyb3VwIjoiMTMyLTA1NC04NDEtNzk5In0.odgpWafSyQQZuc7Va6HkjrZrYLZ3OpjuQAxhVM04mFU

Using HS256

Thanks,

**Comment by holema** [comment]
@namtel-hp 
You can send Emails to any participant, by setting the smtp-settings in the .env.local.
but you can not set for every server it`s own SMTP-server. So to get a enterprise server, also with your own server, you need to get a license from us. We can inject a license in your jitsi-admin server instanze, and send you the license key.
For the jwt-problem @holzi1005 will write you an email, because it is not a topic of Jitsi-Admin :)

**Comment by gcommit** [comment]
I have the same problem. 
I don't get it, how i should create a keycloak client. Everytime i create one, i can't see the secret which i need for the .env.local file

when i call my IP of the jitsi-admin server i get the error 
![Bildschirmfoto 2021-06-11 um 16 34 38](https://user-images.githubusercontent.com/18714033/121703251-ecd11380-cad2-11eb-8d08-f5ee1dfb073e.png)

My KC is running on the same VM, reachable trough port 8080

I tried to built up everything with your documentation, but i can't figure out, how anything has to be configured since i never used keycloak until now.
