### ISSUE TITLE
Docker Image or Build instructions

### ISSUE THREAD

**Issue by emacsen** [H2-invent/jitsi-admin#233]
This project has a number of dependencies which make installation somewhat of a pain, and since both Jitsi and Keycloak are available as Docker containers, it would be nice if this project were also available as a Docker image.

I see there is a docker-compose.yml file in the repo, but sadly it doesn't seem to parse for me, nor does it correspond with the project's needs for external dependencies such as a database connection, etc.

Building this as a Docker project should be fairly straightforward, but I am unfamiliar with those codebase, unfamiliar with PHP and don't speak German, all of which would make this challenging.

Is there a plan to Dockerize Jitsi-Admin? If so, perhaps I could help, and if there isn't, perhaps I could take a quick stab at it.

**Comment by holema** [comment]
hello @emacsen ,
thanks for your question.
Up to now, there are no plans to make a docker jitsi-admin, because we are not in the dockeruniverse. 
So if you have experience I would be so happy if you make a pull request for a docker version.
The Project is based on symfony 5, so this repo is propably a good boilerplate to create a working docker container
https://github.com/dunglas/symfony-docker
Best regards
Emanuel

**Comment by emacsen** [comment]
I'm so sorry! github didn't email me a reply to my notification! I will take a look at this in the next few weeks.

**Comment by h2Entwicklung** [comment]
Hello @emacsen 
We build a complete Dockerinstallation.
You can already pretest it on the freeze branche:
https://github.com/H2-invent/jitsi-admin/tree/freeze/0.72.x
there just hit: installDocker.sh and wait :)
We install all components that are needed for running your jitsi-admin. including SSL encryption.


The full documentation can be found in installDocker.md in the freeze branch.
