### ISSUE TITLE
Instructions for installing my own wildcard certificate

### ISSUE THREAD

**Issue by epigraphe** [H2-invent/jitsi-admin#340]
Good day. We purchased our own wildcard certificate for the domain.
Tell me, please, how to properly install it in the jitsi-admin?

**Comment by holema** [comment]
Hello @epigraphe,

Do you use the docker installation for deployment, or do you use the bare metall installation.

**Comment by epigraphe** [comment]
I am using docker installed according to this instruction https://github.com/H2-invent/jitsi-admin/blob/master/installDocker.md
Prod-environment

**Comment by holema** [comment]
Up to now it is not implemented  to install an own certificate in docker.
We us the Traefik Reverse Proxy to make Reverse Proxying and loadbalancing. Therefor SSL terminiation is done by the traefik. So I can give you a short instruction, but my problem is, that I can`t build it for you, because I don`t have any Wildcard certificate to test.
https://traefik.io/blog/traefik-2-tls-101-23b4fbee81f1/
But I will try to create a boilerplate to impemented an own certificate.

**Comment by epigraphe** [comment]
Thank you. It would be very nice to get some step by step instructions from you.
I tried the instructions on the link above, but I still did not figure out what and where to change.

I suppose this could be useful to many people if this question were in the instructions.

**Comment by holema** [comment]
Hello @epigraphe,

I tried to build a docker sample but I struggle with the fact that I don`t have a wildcard certificate to test it.

Can you write me a private message to entwicklung@h2-invent.com so we can find a solution to create the wildcard installation.

Best regards.

**Comment by holema** [comment]
closed because of inactivity
