### ISSUE TITLE
keycloak port

### ISSUE THREAD

**Issue by MengFanLu1** [H2-invent/jitsi-admin#404]
After docker is installed successfully, what is the port of the keycloak? How do I access the management interface of the keycloak? I use https://keycloak.&lt; yourdomain&gt;” I am deployed on the LAN and then configured the domain name in the hosts file of windows

**Comment by holema** [comment]
Hello @MengFanLu1,

So you can login to the jitsi-admin and everything is working.

The keycloak is not runing on a port and is not accessable directly. We have a reverse proxy in the setup. SO normaly you should be able to get access to the jitsi-admin just by browse to https://keycloak/.< yourdomain> and then you should get the login mask for the keycloak.

The login data to the keycloak are shown after the installation of the jisti-admin.

When you are using an internal installation then you have probaly an issue with the certificats, because then the reverse proxy is not able to get lets encrypt certificats.

**Comment by holema** [comment]
closed because of inactivity
