### ISSUE TITLE
Docker Images on public repo like DockerHub?

### ISSUE THREAD

**Issue by DopeforHope** [H2-invent/jitsi-admin#465]
Currently, one has to build the docker images locally. In order to conveniently use the images with K8s clusters, it would be very helpful to have the Docker Images available at a public repo like Docker Hub. Usually, this is paired with a CI/CD pipeline which pushes the images with every release.

**Comment by Beleggrodion** [comment]
I wanted to make the same request some hours ago (post is still open, some other stuff comes between press enter, see below) 

I'm also intrested into it, because the current setup is not usable for me. I had already a running server with docker (use portainer as webui) with some service (test jitsi setup, collabora office, gitlab, matrix, etc.) and a global traefik instance.

I tried it here for some hours by myself in my local gitlab instance with gitlab-ci, because i had made last year a webui with a websocket server (both php with symfony) for communicate with a python qt app on a raspberry pi. But my modified test docker-compose seems not to work, because the docker logs prints then many errors. So i don't know if the issue is on the docker file or on my gitlab-ci setup (docker in docker build say, all ok)

**Comment by holema** [comment]
Hello @DopeforHope and @Beleggrodion,
Up to now the Docker-image is build during the installer script.
Here we should add a new stage in the github pipeline and push it into the dockerhub repo.

The most intetresting way would be, if there is an already finished gihub action

**Comment by holema** [comment]
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by holema** [comment]
Hello,
we applied for an open source membership are approved now. SO we will upload docker images directly to docker hub in the future.

The repos are:
https://hub.docker.com/r/h2invent/jitsi-admin-main 
for the main jitsi-admin application
and 
https://hub.docker.com/r/h2invent/jitsi-admin-websocket
for the jitsi-admin websocker application.

UP to now there is only one release uploaded. But when they are unlocked we will upload images automaticaly with each action

**Comment by Beleggrodion** [comment]
Hi holema

Thanks for the images. I tried them now if i can run my setup, and i almost worked. I still had some issues but i don't know where the problem coul'd be. some misconfiguration on my side or another problem.  (all docker images in the stack are up and running and also web access is possible, but keycloak has auth issues)

**Comment by holema** [comment]
Hello @Beleggrodion,

so you are able to accesss the jitsi-admin GUI?

**Comment by Beleggrodion** [comment]
yes, i was able to access the jitsi-admin gui and add and remove servers, and create meetings, attend one and so on.

**Comment by holema** [comment]
and this all worked with the docker image. :)

Thanks for testing the docker image, because it was was handy build and uploaded to docker hub.
Now we are building the docker hub upload into the pipeline

**Comment by holema** [comment]
Hello @Beleggrodion,

the jitsi admin docker hub image is now updatet when a new version is released.
Have fun by using the docker image.

I would be very glad when you contribute the k8n configuration to the community.

**Comment by Beleggrodion** [comment]
@holema 
I don't use k8n, i use portainer.io webui together with docker on a ubuntu 22.04 lts server.

The last config is the following (but need to reset all the stuff because guest invites to meetings don't work anymore, and keycloak wants a login, so perhaps i missconfigured something during my tests in kerycloak)

[admin-docker-compose.txt](https://github.com/H2-invent/jitsi-admin/files/13375386/admin-docker-compose.txt)
[admin-docker-env.txt](https://github.com/H2-invent/jitsi-admin/files/13375387/admin-docker-env.txt)
[jitsi-docker-compose.txt](https://github.com/H2-invent/jitsi-admin/files/13375388/jitsi-docker-compose.txt)
[jitsi-docker-env.txt](https://github.com/H2-invent/jitsi-admin/files/13375389/jitsi-docker-env.txt)
[traefik-docker-compose.txt](https://github.com/H2-invent/jitsi-admin/files/13375390/traefik-docker-compose.txt)
